kill:
	docker kill brickhack-backend

pull:
	docker pull alphakilo07/brickhack-backend


run:
	docker run  --rm -d -p 8081:8081 -e PORT='8081' \
		--name brickhack-backend alphakilo07/brickhack-backend

	